lab12/config/routes.rb
Rails.application.routes.draw do
  get 'session/login'
  post 'session/create'
  get 'session/logout'
  resources :users
  root 'index#input'
  get 'index/input'
  get 'index/output'
end

lab12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab12/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :username, presence: true, uniqueness: true

    #def update_last_login_at
        #self.last_login_at = DateTime.now
        #save
    #end 
end

lab12/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionHelper
    
    before_action :require_login

    private

    def require_login
      unless signed_in?
        flash[:danger] = 'Требуется логин'
        redirect_to session_login_url
      end
    end
  end

lab12/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def input
  end

  def output
    if are_equal? params[:sequence], params[:n]
      @result = replace_not_sqr(params[:sequence]).slice_before("ex").to_a.each {|seq| seq.reject! { |item| item == "ex"}}.reject! {|s| s.length < 2}
  
    else
      @result = nil
    end
  end

  private 
  def are_equal? numbers, n
    if numbers.split.all? { |elem| elem.scan(/\D/).empty? } && n.split.all? { |elem| elem.scan(/\D/).empty? }
      n.split.map { |x| Integer(x) }.length == 1 && n.split.map { |x| Integer(x) }[0] == numbers.split.map { |x| Integer(x) }.length
    else
      false
    end 
  end

  def replace_not_sqr numbers
    sequence = numbers.split.map { |x| Integer (x) }
    sequence.each_with_index do |seq, i|
      unless is_sqrt? seq
        sequence[i]="ex"
      end
    end
    sequence
  end

  def is_sqrt? num
    Math.sqrt(num).modulo(Math.sqrt(num).to_i) == 0
  end
end

lab12/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:login, :create]

  def login; end

  def create
    user = User.find_by_username(params[:username])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Неверный логин или пароль'
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

lab12/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :pasword_confirmation)
    end
end

lab12/app/helpers/application_helper.rb
module ApplicationHelper
end

lab12/app/helpers/index_helper.rb
module IndexHelper
end

lab12/app/helpers/session_helper.rb
module SessionHelper
    
    def sign_in(user)
      cookies.signed[:user_id] = { value: user.id, expires: 20.days }
      #user.update_last_login_at
      self.current_user = user
    end
  
    def signed_in?
      !current_user.nil?
    end
  
    def sign_out
      cookies.signed[:user_id] = nil
      self.current_user = nil
    end
  
    def current_user=(user)
      @current_user = user
    end
  
    def current_user
      @current_user ||= User.find_by(id: cookies.signed[:user_id])
    end
end

lab12/app/helpers/users_helper.rb
module UsersHelper
end

lab12/app/views/index/input.html.erb
<h1>Sequence of numbers</h1>
<%= form_tag("/index/output", :method => "get") do %>
    <%= label_tag("Enter the number of numbers:") %>
    <%= text_field_tag(:n)%> <br/><br/>
       
    <%= label_tag("Enter the numbers:") %> 
    <%= text_field_tag(:sequence)%> <br/><br/>
        
    <%= submit_tag ("Вычислить") %> 
<% end %>
<br/>
<p>Show another users<br/>
<%= link_to 'Users', users_path %>
</p>
<%= link_to 'Выйти', session_logout_path %>

lab12/app/views/index/output.html.erb
<h1>Result</h1>

<% if @result == nil%>
    <p>Error. You did not complete the field. Or inconsistency in the amount of data. Or invalid input</p>
<% elsif @result.empty? %>
    <p>There are not sequences</p>
<% else %>
    <table border="1">
    <th>#</th>
    <th>Sequence</th>
    <% @result.each_with_index do |s, i| %>
        <tr><td><%= i=i+1 %></td><td><%= s.join(", ") %></td></tr>
    <% end %>  
    </table>
    <p>Max: <%= @result.max.join(", ") %></p>
    <p>Number of sequence: <%= @result.max.length%></p>
    <%= link_to 'Back', :index_input %>
<% end %>

lab12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab12/app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

lab12/app/views/session/login.html.erb
<h1>Log In</h1>
<%= form_tag url_for(controller: :session, action: :create), method: 'post' do |form| %>
    <div class="field">
        <%= label_tag :username %>
        <%= text_field_tag :username %>
    </div>
    <div class="field">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
    </div>
    <div class="actions">
        <%= submit_tag "Log In" %>
    </div>
<% end %>
<%= link_to 'Зарегистрироваться', new_user_path %>

lab12/app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

lab12/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab12/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :index_input %>

lab12/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', :index_input %>

lab12/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', session_login_path %>

lab12/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Back', :index_input %>