lab11/config/routes.rb
Rails.application.routes.draw do
  root 'index#input'
  get 'index/input'
  get 'index/output'
  get 'cached' => 'index#cached'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

lab11/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab11/app/models/result.rb
class Result < ApplicationRecord
    validates:input ,uniqueness: true

    class<<self
        def generate_result(n, sequence)
            
            if are_equal? sequence, n
                if exists?(input:sequence)
                    res = eval(find_by(input: sequence).output)
                else
                    res = replace_not_sqr(sequence).slice_before("ex").to_a.each {|seq| seq.reject! { |item| item == "ex"}}.reject! {|s| s.length < 2}
                    create(input: sequence, output: res.to_s)
                end
            else
                res = nil
            end
            res
        end

        private 
        def are_equal? numbers, n
            if numbers.split.all? { |elem| elem.scan(/\D/).empty? } && n.split.all? { |elem| elem.scan(/\D/).empty? }
                n.split.map { |x| Integer(x) }.length == 1 && n.split.map { |x| Integer(x) }[0] == numbers.split.map { |x| Integer(x) }.length
            else
                false
            end 
        end

        def replace_not_sqr numbers
            sequence = numbers.split.map { |x| Integer (x) }
            sequence.each_with_index do |seq, i|
                unless is_sqrt? seq
                    sequence[i]="ex"
                end
            end
            sequence
        end

        def is_sqrt? num
            Math.sqrt(num).modulo(Math.sqrt(num).to_i) == 0
        end

    end
end

lab11/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab11/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def input
  end

  def cached
    result = Result.all.map{|var| [in: var.input, out: var.output] }
    p Result.all
    respond_to do|format|
      format.xml{render xml: result.to_xml}
    end
  end

  def output
    @result = Result.generate_result(params[:n], params[:sequence])
  end
end

lab11/app/helpers/application_helper.rb
module ApplicationHelper
end

lab11/app/helpers/index_helper.rb
module IndexHelper
end

lab11/app/views/index/input.html.erb
<h1>Sequence of numbers</h1>

<form action="<%= index_output_url %>">
 <p>Enter the number of numbers:</p>
 <p><input name="n"/></p>
 <p>Enter the numbers:</p>
 <p><input name="sequence"/></p>
 <p><input type="submit" value="Submit"></p>
</form>

lab11/app/views/index/output.html.erb
<h1>Result</h1>


<% if @result == nil %>
    <p>There are not sequences or invalid input</p>
<% else %>
    <table border="1">
    <th>#</th>
    <th>Sequence</th>
    <% @result.each_with_index do |s, i| %>
        <tr><td><%= i=i+1 %></td><td><%= s.join(", ") %></td></tr>
    <% end %>  
    </table>
    <p>Max: <%= @result.max.join(", ") %></p>
    <p>Number of sequence: <%= @result.max.length%></p>
<% end %>